version: '3'
name: bcbk2023
services:
  web:
    build: .
    ports:
      - '8080:8080'
    restart: on-failure
    environment:
      - MONGO_URI=mongodb://mongo:27017/test
    command: npm run start:prod

  database:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db

volumes:
  data:
