name: Tests

on:
  workflow_call:
    inputs:
      path:
        description: Path to test
        required: false
        default: '.'

jobs:
  lint:
    name: Lint Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Go to directory
        run: cd ${{ inputs.path }}
      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install yarn
        run: npm install --global yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Perform Lint Test
        run: yarn lint
  test-unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Go to directory
        run: cd ${{ inputs.path }}
      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install yarn
        run: npm install --global yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Execute Unit Test
        run: yarn test:unit
  test-integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Go to directory
        run: cd ${{ inputs.path }}
      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install yarn
        run: npm install --global yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Execute Unit Test
        run: yarn test:integration
  coverage:
    name: Coverage Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Go to directory
        run: cd ${{ inputs.path }}
      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install yarn
        run: npm install --global yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests and collect coverage
        run: yarn test:coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage